// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGsMV0UYAPRi0qCTRS_Q0CHKDKon50ef0',
    appId: '1:499508142262:web:752025d2e589fc19474617',
    messagingSenderId: '499508142262',
    projectId: 'acoustic-scarab-432308-b5',
    authDomain: 'acoustic-scarab-432308-b5.firebaseapp.com',
    storageBucket: 'acoustic-scarab-432308-b5.appspot.com',
    measurementId: 'G-KNJTRNFBQT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoV9gfpK56G23gCnhTXlDLaH8-YTElsCQ',
    appId: '1:499508142262:android:e4125b2446362419474617',
    messagingSenderId: '499508142262',
    projectId: 'acoustic-scarab-432308-b5',
    storageBucket: 'acoustic-scarab-432308-b5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvNNEPAn8KEXwcyGMnrHVwifDRHd6fs0Y',
    appId: '1:499508142262:ios:e2fb20664a9e28b8474617',
    messagingSenderId: '499508142262',
    projectId: 'acoustic-scarab-432308-b5',
    storageBucket: 'acoustic-scarab-432308-b5.appspot.com',
    iosBundleId: 'com.example.tedxwordle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvNNEPAn8KEXwcyGMnrHVwifDRHd6fs0Y',
    appId: '1:499508142262:ios:e2fb20664a9e28b8474617',
    messagingSenderId: '499508142262',
    projectId: 'acoustic-scarab-432308-b5',
    storageBucket: 'acoustic-scarab-432308-b5.appspot.com',
    iosBundleId: 'com.example.tedxwordle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGsMV0UYAPRi0qCTRS_Q0CHKDKon50ef0',
    appId: '1:499508142262:web:beb86676f05fa797474617',
    messagingSenderId: '499508142262',
    projectId: 'acoustic-scarab-432308-b5',
    authDomain: 'acoustic-scarab-432308-b5.firebaseapp.com',
    storageBucket: 'acoustic-scarab-432308-b5.appspot.com',
    measurementId: 'G-TQKNMNMR0D',
  );

}